# -*- coding: utf-8 -*-
"""numpy + pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UEbOliN5ANoycDaqE72geUwHci-D0xG1
"""

import pandas as pd
import numpy as np
import seaborn as sns

df = sns.load_dataset("diamonds")
#?sns.load_dataset

df.head()

df.mean()

df["price"].mean()

df.median()

df

df["price"].min()

df["price"].max()

sns.distplot(df["price"]);

sns.distplot(df["table"], kde = False);

df.std() #vrati smerodaj.odchylku - druha odmoc z rozptylu (rozptyl / n-1)

df["price"].sum()

df["price"].mean() # average

df.describe()

df.describe().T # or df.describe().transpose()